In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\asus\anaconda3\lib\site-packages (4.18.1)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.24.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\asus\anaconda3\lib\site-packages (from selenium) (4.10.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: cffi>=1.14 in c:\users\asus\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\asus\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\asus\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\asus\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\asus\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [121]:
#Imports
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException,ElementNotInteractableException
 #Importing Exception
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import re
import requests
from selenium.webdriver.support import expected_conditions as EC

In [ ]:
Q-1

In [3]:
driver= webdriver.Chrome()
driver.maximize_window()
#chrome

In [4]:
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/')
time.sleep(2)
#open url

In [5]:
Search = driver.find_element(By.XPATH, '//input[@class="cdx-text-input__input"]' )
Search.send_keys( 'List of most-viewed YouTube videos')
#Search the above topic

In [6]:
Search_click= driver.find_element(By.XPATH, '//button[@class="cdx-button cdx-button--action-default cdx-button--weight-normal cdx-button--size-medium cdx-button--framed cdx-search-input__end-button"]')
Search_click.click()
#click the search

In [7]:
Rank= []
Name= []
Artist= []
Upload_date= []
Views= []
#create empty fields

In [13]:
name = driver.find_elements(By.XPATH, '//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td')

for i in name:
    Name.append(i.text)
    
    
artists=  driver.find_elements(By.XPATH, '//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[2]')
for i in artists:
    Artist.append(i.text)
    
    
upload_date= driver.find_elements(By.XPATH, '//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[4]')
for i in upload_date:
    Upload_date.append(i.text)
    
    
views= driver.find_elements(By.XPATH, '//table[@class="sortable wikitable sticky-header static-row-numbers sort-under col3center col4right jquery-tablesorter"]/tbody/tr/td[3]')
for i in views:
    Views.append(i.text)
    
#Let's create a function to get the Match details

In [14]:
import pandas as pd

In [16]:
You_tube_videos=pd.DataFrame({})
You_tube_videos['Video Name']=Name[0:30]
You_tube_videos['Artist']=Artist[0:30]
You_tube_videos['Upload Date']=Upload_date[0:30]
You_tube_videos['Views (Billions)']=Views[0:30]
You_tube_videos
#let's create dataframe

,Video Name,Artist,Upload Date,Views (Billions)
0,"""Baby Shark Dance""[7]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",14.32
1,Pinkfong Baby Shark - Kids' Songs & Stories,Luis Fonsi,"January 12, 2017",8.41
2,14.32,LooLoo Kids - Nursery Rhymes and Children's Songs,"October 8, 2016",6.89
3,"June 17, 2016",Cocomelon - Nursery Rhymes,"May 2, 2018",6.66
4,[A],Ed Sheeran,"January 30, 2017",6.23
5,"""Despacito""[10]",Wiz Khalifa,"April 6, 2015",6.22
6,Luis Fonsi,Cocomelon - Nursery Rhymes,"May 24, 2018",6.01
7,8.41,ChuChu TV Nursery Rhymes & Kids Songs,"March 6, 2014",5.75
8,"January 12, 2017",Mark Ronson,"November 19, 2014",5.18
9,[B],Psy,"July 15, 2012",5.10
10,"""Johny Johny Yes Papa""[18]",Miroshka TV,"February 27, 2018",5.09
11,LooLoo Kids - Nursery Rhymes and Children's Songs,Ultra Records,"April 5, 2018",4.59
12,6.89,Get Movies,"January 31, 2012",4.57
13,"October 8, 2016",Crazy Frog,"June 16, 2009",4.45
14,,Maroon 5,"January 14, 2015",4.02
15,"""Bath Song""[19]",Cocomelon - Nursery Rhymes,"June 25, 2018",4.01
16,Cocomelon - Nursery Rhymes,OneRepublic,"May 31, 2013",4.00
17,6.66,Jingle Toons,"June 14, 2018",3.98
18,"May 2, 2018",Katy Perry,"September 5, 2013",3.98
19,,Shakira,"June 4, 2010",3.89
20,"""Shape of You""[20]",Justin Bieber,"October 22, 2015",3.78
21,Ed Sheeran,T-Series Bhakti Sagar,"May 10, 2011",3.77
22,6.23,Kiddiestv Hindi - Nursery Rhymes & Kids Songs,"January 26, 2018",3.76
23,"January 30, 2017",Ed Sheeran,"October 7, 2014",3.75
24,[C],Ed Sheeran,"November 9, 2017",3.70
25,"""See You Again""[23]",Katy Perry,"February 20, 2014",3.70
26,Wiz Khalifa,Passenger,"July 25, 2012",3.64
27,6.22,Alan Walker,"December 3, 2015",3.60
28,"April 6, 2015",Maroon 5,"May 31, 2018",3.58
29,[D],Major Lazer Official,"March 22, 2015",3.57

In [ ]:
Q-2

In [71]:
driver= webdriver.Chrome()
driver.maximize_window()

In [72]:
driver.get('https://www.bcci.tv/.')
time.sleep(2)

In [73]:
Search= driver.find_element(By.XPATH, '/html/body/header/div[1]/div/button[1]/img')
Search.click()

In [74]:
Select= driver.find_element(By.XPATH, '//input[@class="form-control border rounded-pill"]')
Select.send_keys('International fixtures')

In [75]:
Search_click= driver.find_element(By.XPATH, '/html/body/header/div[2]/form/div/div/div/span[2]/button')
Search_click.click()

In [81]:
Fixture= driver.find_element(By.XPATH, '/html/body/header/div[3]/div[2]/ul/div[1]/a[2]')
Fixture.click()

In [114]:
Series=[]
Date=[] 
Time=[]
Place=[]

In [115]:
series= driver.find_elements(By.XPATH, '//div[@class="match-card-middle d-flex"]')
for i in series:
    Series.append(i.text)
    

    
date= driver.find_elements(By.XPATH, '//div[@class="match-dates ng-binding"]')
for i in date:
    Date.append(i.text)
    
time= driver.find_elements(By.XPATH, '//div[@class="match-time no-margin ng-binding"]')
for i in time:
    Time.append(i.text)
    
place= driver.find_elements(By.XPATH, '//span[@class="ng-binding ng-scope"]')
for i in place:
    Place.append(i.text)

In [116]:
IF_ICC=pd.DataFrame({})
IF_ICC['Series']=Series
IF_ICC['Date']=Date
IF_ICC['Time']=Time
IF_ICC['Place']=Place
IF_ICC

,Series,Date,Time,Place
0,India\nIreland,"5 JUNE, 2024",8:00 PM IST,"Nassau County International Cricket Stadium,"
1,India\nPakistan,"9 JUNE, 2024",8:00 PM IST,"Nassau County International Cricket Stadium,"
2,United States Of America\nIndia,"12 JUNE, 2024",8:00 PM IST,"Nassau County International Cricket Stadium,"
3,Canada\nIndia,"15 JUNE, 2024",8:00 PM IST,"Central Broward Park & Broward County Stadium,..."
4,Zimbabwe\nIndia,"6 JULY, 2024",8:00 PM IST,"Harare Sports Club,"
5,Zimbabwe\nIndia,"7 JULY, 2024",8:00 PM IST,"Harare Sports Club,"
6,Zimbabwe\nIndia,"10 JULY, 2024",8:00 PM IST,"Harare Sports Club,"
7,Zimbabwe\nIndia,"13 JULY, 2024",8:00 PM IST,"Harare Sports Club,"
8,Zimbabwe\nIndia,"14 JULY, 2024",8:00 PM IST,"Harare Sports Club,"

In [ ]:
Q-8

In [360]:
driver=webdriver.Chrome()
driver.maximize_window()

In [361]:
driver.get('https://archive.ics.uci.edu/')
time.sleep(2)

In [362]:
dataset=driver.find_element(By.XPATH, "/html/body/div/div[1]/div[1]/main/div/div[1]/div/div/div/a[1]")
driver.get(dataset.get_attribute('href'))

In [367]:
Dataset_Name=[] 
Data_Type=[]
Task=[] 
Attribute_Type=[] 
No_of_Instances=[] 
No_of_Attribute=[] 
Year=[]

In [364]:
Expand= driver.find_element(By.XPATH, '//span[@class="swap-on text-primary-content"]')
Expand.click()

In [378]:
Name= driver.find_elements(By.XPATH, '//h2[@class="truncate text-primary"]')
for i in Name:
    Dataset_Name.append(i.text)
    
type= driver.find_elements(By.XPATH, '//div[@class="flex flex-col gap-1"]/div/div/div/div/div[2]/span')
for i in type:
    Data_Type.append(i.text)
    
task= driver.find_elements(By.XPATH, '//div[@class="flex flex-col gap-1"]/div/div/div/div/div/span')
for i in task:
    Task.append(i.text)
    
    

    

    
    

    
attribute= driver.find_elements(By.XPATH, '//tbody[@class="border"]/tr/td[2]')
for i in attribute:
    Attribute_Type.append(i.text)
    
    
instances= driver.find_elements(By.XPATH, '//div[@class="flex flex-col gap-1"]/div/div/div/div/div[3]/span')
for i in instances:
    No_of_Instances.append(i.text)
    
    
attribute= driver.find_elements(By.XPATH,'/html/body/div/div[1]/div[1]/main/div/div[2]/div[2]/div[1]/div[1]/div[2]/div/div[4]/span')
for i in attribute:
    No_of_Attribute.append(i.text)
    
    
year= driver.find_elements(By.XPATH, '//table[@class="col-span-full my-2 table sm:col-start-2"]/tbody/tr/td[3]')
for i in year:
    Year.append(i.text)

In [376]:
print(Attribute_Type)

['Real', 'Integer, Real', 'Categorical, Integer, Real', 'Real', 'Categorical, Integer', 'Real, Integer', 'Real', 'Integer, Real', 'Real', 'Categorical, Integer', 'Real', 'Integer, Real', 'Categorical, Integer, Real', 'Real', 'Categorical, Integer', 'Real, Integer', 'Real', 'Integer, Real', 'Real', 'Categorical, Integer', 'Real', 'Integer, Real', 'Categorical, Integer, Real', 'Real', 'Categorical, Integer', 'Real, Integer', 'Real', 'Integer, Real', 'Real', 'Categorical, Integer', 'Real', 'Integer, Real', 'Categorical, Integer, Real', 'Real', 'Categorical, Integer', 'Real, Integer', 'Real', 'Integer, Real', 'Real', 'Categorical, Integer', 'Real', 'Integer, Real', 'Categorical, Integer, Real', 'Real', 'Categorical, Integer', 'Real, Integer', 'Real', 'Integer, Real', 'Real', 'Categorical, Integer']

In [374]:
print(No_of_Instances)

['150 Instances', '150 Instances', '150 Instances', '13.61K Instances', '303 Instances', '3.81K Instances', '48.84K Instances', '900 Instances', '569 Instances', '178 Instances', '4.9K Instances', '1 Instances', '150 Instances', '13.61K Instances', '303 Instances', '3.81K Instances', '48.84K Instances', '900 Instances', '569 Instances', '178 Instances', '4.9K Instances', '1 Instances', '150 Instances', '13.61K Instances', '303 Instances', '3.81K Instances', '48.84K Instances', '900 Instances', '569 Instances', '178 Instances', '4.9K Instances', '1 Instances']

In [381]:
UCI_ML=pd.DataFrame({})
UCI_ML['Dataset Name']=Dataset_Name 
UCI_ML['Attribute Type']=Attribute_Type
UCI_ML['No of Instances']=No_of_Instances
UCI_ML['No of Attribute']= No_of_Attribute
UCI_ML['Year']=Year
UCI_ML

ValueError: Length of values (52) does not match length of index (70)

# Q-6

In [220]:
driver=webdriver.Chrome()
driver.maximize_window()

In [221]:
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/')
time.sleep(2)

In [222]:
Book_Name=[] 
Author_Name=[] 
Volumes_Sold=[]
Publisher=[] 
Genre=[]

In [223]:
name= driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[2]')
for i in name:
    Book_Name.append(i.text)
    
    
Author= driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[3]')
for i in Author:
    Author_Name.append(i.text)
    
Volumes= driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[4]')
for i in Volumes:
    Volumes_Sold.append(i.text)
    
publisher= driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[5]')
for i in publisher:
    Publisher.append(i.text)
    
genre= driver.find_elements(By.XPATH, '//table[@class="in-article sortable"]/tbody/tr/td[6]')
for i in genre:
    Genre.append(i.text)

In [217]:
print(Book_Name)

['Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours", 'Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours", 'Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours", 'Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours", 'Da Vinci Code,The', 'Harry Potter and the Deathly Hallows', "Harry Potter and the Philosopher's Stone", 'Harry Potter and the Order of the Phoenix', 'Fifty Shades of Grey', 'Harry Potter and the Goblet of Fire', 'Harry Potter and the Chamber of Secrets', 'Harry Potter and the Prisoner of Azkaban', 'Angels and Demons', "Harry Potter and the Half-blood Prince:Children's Edition", 'Fifty Shades Darker', 'Twilight', 'Girl with the Dragon Tattoo,The:Millennium Trilogy', 'Fifty Shades Freed', 'Lost Symbol,The', 'New Moon', 'Deception Point', 'Eclipse', 'Lovely Bones,The', 'Curious Incident of the Dog in the Night-time,The', 'Digital Fortress', 'Short History of Nearly Everything,A', 'Girl Who Played with Fire,The:Millennium Trilogy', 'Breaking Dawn', 'Very Hungry Caterpillar,The:The Very Hungry Caterpillar', 'Gruffalo,The', "Jamie's 30-Minute Meals", 'Kite Runner,The', 'One Day', 'Thousand Splendid Suns,A', "Girl Who Kicked the Hornets' Nest,The:Millennium Trilogy", "Time Traveler's Wife,The", 'Atonement', "Bridget Jones's Diary:A Novel", 'World According to Clarkson,The', "Captain Corelli's Mandolin", 'Sound of Laughter,The', 'Life of Pi', 'Billy Connolly', 'Child Called It,A', "Gruffalo's Child,The", "Angela's Ashes:A Memoir of a Childhood", 'Birdsong', 'Northern Lights:His Dark Materials S.', 'Labyrinth', 'Harry Potter and the Half-blood Prince', 'Help,The', 'Man and Boy', 'Memoirs of a Geisha', "No.1 Ladies' Detective Agency,The:No.1 Ladies' Detective Agency S.", 'Island,The', 'PS, I Love You', 'You are What You Eat:The Plan That Will Change Your Life', 'Shadow of the Wind,The', 'Tales of Beedle the Bard,The', 'Broker,The', "Dr. Atkins' New Diet Revolution:The No-hunger, Luxurious Weight Loss P", 'Subtle Knife,The:His Dark Materials S.', 'Eats, Shoots and Leaves:The Zero Tolerance Approach to Punctuation', "Delia's How to Cook:(Bk.1)", 'Chocolat', 'Boy in the Striped Pyjamas,The', "My Sister's Keeper", 'Amber Spyglass,The:His Dark Materials S.', 'To Kill a Mockingbird', 'Men are from Mars, Women are from Venus:A Practical Guide for Improvin', 'Dear Fatty', 'Short History of Tractors in Ukrainian,A', 'Hannibal', 'Lord of the Rings,The', 'Stupid White Men:...and Other Sorry Excuses for the State of the Natio', 'Interpretation of Murder,The', 'Sharon Osbourne Extreme:My Autobiography', 'Alchemist,The:A Fable About Following Your Dream', "At My Mother's Knee ...:and Other Low Joints", 'Notes from a Small Island', 'Return of the Naked Chef,The', 'Bridget Jones: The Edge of Reason', "Jamie's Italy", 'I Can Make You Thin', 'Down Under', 'Summons,The', 'Small Island', 'Nigella Express', 'Brick Lane', "Memory Keeper's Daughter,The", 'Room on the Broom', 'About a Boy', 'My Booky Wook', 'God Delusion,The', '"Beano" Annual,The', 'White Teeth', 'House at Riverton,The', 'Book Thief,The', 'Nights of Rain and Stars', 'Ghost,The', 'Happy Days with the Naked Chef', 'Hunger Games,The:Hunger Games Trilogy', "Lost Boy,The:A Foster Child's Search for the Love of a Family", "Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours"]

In [218]:
print(Author_Name)

['Brown, Dan', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'James, E. L.', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'Brown, Dan', 'Rowling, J.K.', 'James, E. L.', 'Meyer, Stephenie', 'Larsson, Stieg', 'James, E. L.', 'Brown, Dan', 'Meyer, Stephenie', 'Brown, Dan', 'Meyer, Stephenie', 'Sebold, Alice', 'Haddon, Mark', 'Brown, Dan', 'Bryson, Bill', 'Larsson, Stieg', 'Meyer, Stephenie', 'Carle, Eric', 'Donaldson, Julia', 'Oliver, Jamie', 'Hosseini, Khaled', 'Nicholls, David', 'Hosseini, Khaled', 'Larsson, Stieg', 'Niffenegger, Audrey', 'McEwan, Ian', 'Fielding, Helen', 'Clarkson, Jeremy', 'Bernieres, Louis de', 'Kay, Peter', 'Martel, Yann', 'Stephenson, Pamela', 'Pelzer, Dave', 'Donaldson, Julia', 'McCourt, Frank', 'Faulks, Sebastian', 'Pullman, Philip', 'Mosse, Kate', 'Rowling, J.K.', 'Stockett, Kathryn', 'Parsons, Tony', 'Golden, Arthur', 'McCall Smith, Alexander', 'Hislop, Victoria', 'Ahern, Cecelia', 'McKeith, Gillian', 'Zafon, Carlos Ruiz', 'Rowling, J.K.', 'Grisham, John', 'Atkins, Robert C.', 'Pullman, Philip', 'Truss, Lynne', 'Smith, Delia', 'Harris, Joanne', 'Boyne, John', 'Picoult, Jodi', 'Pullman, Philip', 'Lee, Harper', 'Gray, John', 'French, Dawn', 'Lewycka, Marina', 'Harris, Thomas', 'Tolkien, J. R. R.', 'Moore, Michael', 'Rubenfeld, Jed', 'Osbourne, Sharon', 'Coelho, Paulo', "O'Grady, Paul", 'Bryson, Bill', 'Oliver, Jamie', 'Fielding, Helen', 'Oliver, Jamie', 'McKenna, Paul', 'Bryson, Bill', 'Grisham, John', 'Levy, Andrea', 'Lawson, Nigella', 'Ali, Monica', 'Edwards, Kim', 'Donaldson, Julia', 'Hornby, Nick', 'Brand, Russell', 'Dawkins, Richard', '0', 'Smith, Zadie', 'Morton, Kate', 'Zusak, Markus', 'Binchy, Maeve', 'Harris, Robert', 'Oliver, Jamie', 'Collins, Suzanne', 'Pelzer, Dave', 'Oliver, Jamie', 'Brown, Dan', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'James, E. L.', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'Brown, Dan', 'Rowling, J.K.', 'James, E. L.', 'Meyer, Stephenie', 'Larsson, Stieg', 'James, E. L.', 'Brown, Dan', 'Meyer, Stephenie', 'Brown, Dan', 'Meyer, Stephenie', 'Sebold, Alice', 'Haddon, Mark', 'Brown, Dan', 'Bryson, Bill', 'Larsson, Stieg', 'Meyer, Stephenie', 'Carle, Eric', 'Donaldson, Julia', 'Oliver, Jamie', 'Hosseini, Khaled', 'Nicholls, David', 'Hosseini, Khaled', 'Larsson, Stieg', 'Niffenegger, Audrey', 'McEwan, Ian', 'Fielding, Helen', 'Clarkson, Jeremy', 'Bernieres, Louis de', 'Kay, Peter', 'Martel, Yann', 'Stephenson, Pamela', 'Pelzer, Dave', 'Donaldson, Julia', 'McCourt, Frank', 'Faulks, Sebastian', 'Pullman, Philip', 'Mosse, Kate', 'Rowling, J.K.', 'Stockett, Kathryn', 'Parsons, Tony', 'Golden, Arthur', 'McCall Smith, Alexander', 'Hislop, Victoria', 'Ahern, Cecelia', 'McKeith, Gillian', 'Zafon, Carlos Ruiz', 'Rowling, J.K.', 'Grisham, John', 'Atkins, Robert C.', 'Pullman, Philip', 'Truss, Lynne', 'Smith, Delia', 'Harris, Joanne', 'Boyne, John', 'Picoult, Jodi', 'Pullman, Philip', 'Lee, Harper', 'Gray, John', 'French, Dawn', 'Lewycka, Marina', 'Harris, Thomas', 'Tolkien, J. R. R.', 'Moore, Michael', 'Rubenfeld, Jed', 'Osbourne, Sharon', 'Coelho, Paulo', "O'Grady, Paul", 'Bryson, Bill', 'Oliver, Jamie', 'Fielding, Helen', 'Oliver, Jamie', 'McKenna, Paul', 'Bryson, Bill', 'Grisham, John', 'Levy, Andrea', 'Lawson, Nigella', 'Ali, Monica', 'Edwards, Kim', 'Donaldson, Julia', 'Hornby, Nick', 'Brand, Russell', 'Dawkins, Richard', '0', 'Smith, Zadie', 'Morton, Kate', 'Zusak, Markus', 'Binchy, Maeve', 'Harris, Robert', 'Oliver, Jamie', 'Collins, Suzanne', 'Pelzer, Dave', 'Oliver, Jamie', 'Brown, Dan', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'James, E. L.', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'Brown, Dan', 'Rowling, J.K.', 'James, E. L.', 'Meyer, Stephenie', 'Larsson, Stieg', 'James, E. L.', 'Brown, Dan', 'Meyer, Stephenie', 'Brown, Dan', 'Meyer, Stephenie', 'Sebold, Alice', 'Haddon, Mark', 'Brown, Dan', 'Bryson, Bill', 'Larsson, Stieg', 'Meyer, Stephenie', 'Carle, Eric', 'Donaldson, Julia', 'Oliver, Jamie', 'Hosseini, Khaled', 'Nicholls, David', 'Hosseini, Khaled', 'Larsson, Stieg', 'Niffenegger, Audrey', 'McEwan, Ian', 'Fielding, Helen', 'Clarkson, Jeremy', 'Bernieres, Louis de', 'Kay, Peter', 'Martel, Yann', 'Stephenson, Pamela', 'Pelzer, Dave', 'Donaldson, Julia', 'McCourt, Frank', 'Faulks, Sebastian', 'Pullman, Philip', 'Mosse, Kate', 'Rowling, J.K.', 'Stockett, Kathryn', 'Parsons, Tony', 'Golden, Arthur', 'McCall Smith, Alexander', 'Hislop, Victoria', 'Ahern, Cecelia', 'McKeith, Gillian', 'Zafon, Carlos Ruiz', 'Rowling, J.K.', 'Grisham, John', 'Atkins, Robert C.', 'Pullman, Philip', 'Truss, Lynne', 'Smith, Delia', 'Harris, Joanne', 'Boyne, John', 'Picoult, Jodi', 'Pullman, Philip', 'Lee, Harper', 'Gray, John', 'French, Dawn', 'Lewycka, Marina', 'Harris, Thomas', 'Tolkien, J. R. R.', 'Moore, Michael', 'Rubenfeld, Jed', 'Osbourne, Sharon', 'Coelho, Paulo', "O'Grady, Paul", 'Bryson, Bill', 'Oliver, Jamie', 'Fielding, Helen', 'Oliver, Jamie', 'McKenna, Paul', 'Bryson, Bill', 'Grisham, John', 'Levy, Andrea', 'Lawson, Nigella', 'Ali, Monica', 'Edwards, Kim', 'Donaldson, Julia', 'Hornby, Nick', 'Brand, Russell', 'Dawkins, Richard', '0', 'Smith, Zadie', 'Morton, Kate', 'Zusak, Markus', 'Binchy, Maeve', 'Harris, Robert', 'Oliver, Jamie', 'Collins, Suzanne', 'Pelzer, Dave', 'Oliver, Jamie', 'Brown, Dan', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'James, E. L.', 'Rowling, J.K.', 'Rowling, J.K.', 'Rowling, J.K.', 'Brown, Dan', 'Rowling, J.K.', 'James, E. L.', 'Meyer, Stephenie', 'Larsson, Stieg', 'James, E. L.', 'Brown, Dan', 'Meyer, Stephenie', 'Brown, Dan', 'Meyer, Stephenie', 'Sebold, Alice', 'Haddon, Mark', 'Brown, Dan', 'Bryson, Bill', 'Larsson, Stieg', 'Meyer, Stephenie', 'Carle, Eric', 'Donaldson, Julia', 'Oliver, Jamie', 'Hosseini, Khaled', 'Nicholls, David', 'Hosseini, Khaled', 'Larsson, Stieg', 'Niffenegger, Audrey', 'McEwan, Ian', 'Fielding, Helen', 'Clarkson, Jeremy', 'Bernieres, Louis de', 'Kay, Peter', 'Martel, Yann', 'Stephenson, Pamela', 'Pelzer, Dave', 'Donaldson, Julia', 'McCourt, Frank', 'Faulks, Sebastian', 'Pullman, Philip', 'Mosse, Kate', 'Rowling, J.K.', 'Stockett, Kathryn', 'Parsons, Tony', 'Golden, Arthur', 'McCall Smith, Alexander', 'Hislop, Victoria', 'Ahern, Cecelia', 'McKeith, Gillian', 'Zafon, Carlos Ruiz', 'Rowling, J.K.', 'Grisham, John', 'Atkins, Robert C.', 'Pullman, Philip', 'Truss, Lynne', 'Smith, Delia', 'Harris, Joanne', 'Boyne, John', 'Picoult, Jodi', 'Pullman, Philip', 'Lee, Harper', 'Gray, John', 'French, Dawn', 'Lewycka, Marina', 'Harris, Thomas', 'Tolkien, J. R. R.', 'Moore, Michael', 'Rubenfeld, Jed', 'Osbourne, Sharon', 'Coelho, Paulo', "O'Grady, Paul", 'Bryson, Bill', 'Oliver, Jamie', 'Fielding, Helen', 'Oliver, Jamie', 'McKenna, Paul', 'Bryson, Bill', 'Grisham, John', 'Levy, Andrea', 'Lawson, Nigella', 'Ali, Monica', 'Edwards, Kim', 'Donaldson, Julia', 'Hornby, Nick', 'Brand, Russell', 'Dawkins, Richard', '0', 'Smith, Zadie', 'Morton, Kate', 'Zusak, Markus', 'Binchy, Maeve', 'Harris, Robert', 'Oliver, Jamie', 'Collins, Suzanne', 'Pelzer, Dave', 'Oliver, Jamie']

In [224]:
Novel=pd.DataFrame({})
Novel['Book Name']=Book_Name
Novel['Author Name']= Author_Name
Novel['Volumes Sold']=Volumes_Sold
Novel['Publisher']=Publisher
Novel['Genre']=Genre
Novel

,Book Name,Author Name,Volumes Sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

# Q-5

In [341]:
driver=webdriver.Chrome()
driver.maximize_window()

In [342]:
driver.get('https://www.billboard.com/')
time.sleep(2)

In [343]:
Select= driver.find_element(By.XPATH, '/html/body/div[3]/header/div/div[3]/div/nav/ul/li[1]/a')
Select.click()

In [344]:
Song_Name=[]
Artist_Name=[] 
Last_Week_Rank=[] 
Peak_Rank=[]
Weeks_on_Board=[]

In [348]:
name= driver.find_elements(By.XPATH, '//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li/h3')
for i in name:
    Song_Name.append(i.text)
    
    
    
Artist= driver.find_elements(By.XPATH, '//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li/span')
for i in Artist:
    Artist_Name.append(i.text)
    
    
rank= driver.find_elements(By.XPATH, '//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[4]/span')
for i in rank:
    Last_Week_Rank.append(i.text)
    
    
peak= driver.find_elements(By.XPATH, '//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[5]/span')
for i in peak:
    Peak_Rank.append(i.text)
    
    
weeks= driver.find_elements(By.XPATH, '//div[@class="o-chart-results-list-row-container"]/ul/li[4]/ul/li[6]/span')
for i in weeks:
    Weeks_on_Board.append(i.text)

In [ ]:
print(Last_Week_Rank)

In [243]:
print(Artist_Name)

['Future, Metro Boomin, Travis Scott & Playboi Carti', 'Benson Boone', 'Teddy Swims', 'Hozier', 'Future, Metro Boomin & Travis Scott', 'Jack Harlow', 'Future & Metro Boomin', 'Future, Metro Boomin & The Weeknd', 'Ariana Grande', 'Beyonce', '¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', 'Future & Metro Boomin', 'Olivia Rodrigo', 'Zach Bryan Featuring Kacey Musgraves', 'Taylor Swift', 'Tate McRae', 'Noah Kahan', 'Tyla', 'Future & Metro Boomin', 'Djo', 'Doja Cat', 'SZA', 'Future & Metro Boomin', 'Luke Combs', 'SZA', 'Future & Metro Boomin', 'Sexyy Red', 'Flo Milli', '21 Savage', '4Batz Featuring Drake', 'Bryson Tiller', 'Future & Metro Boomin', 'Muni Long', 'Sabrina Carpenter', 'Future & Metro Boomin', 'Morgan Wallen Featuring Eric Church', 'Future, Metro Boomin & Rick Ross', 'HARDY', 'Future & Metro Boomin', 'Future & Metro Boomin', 'Dua Lipa', 'Doja Cat', 'Cardi B', 'Benson Boone', 'Justin Timberlake', 'Taylor Swift', 'Chayce Beckham', 'GloRilla', 'Luke Combs', 'Parker McCollum', 'Future & Metro Boomin', 'Dasha', 'Future & Metro Boomin', 'Jessie Murph & Jelly Roll', 'Xavi', 'Tate McRae', 'Olivia Rodrigo', 'Lainey Wilson', 'Ariana Grande', 'Ariana Grande', 'Future & Metro Boomin', 'BossMan Dlow', '310babii', 'Michael Marcagi', 'Nicki Minaj Featuring Lil Uzi Vert', 'YG Marley', 'Thomas Rhett Featuring Morgan Wallen', 'Peso Pluma, Tito Double P & Joel de La P', 'Artemas', 'Dua Lipa', 'Shakira & Cardi B', 'Xavi', 'The Weeknd, Jennie & Lily Rose Depp', 'Olivia Rodrigo', 'BigXthaPlug', 'Don Toliver', 'JID Featuring 21 Savage & Baby Tate', 'Bailey Zimmerman', 'Ariana Grande', 'Fuerza Regida', 'Nicki Minaj', 'FloyyMenor X Cris Mj', 'Kane Brown', 'Yeat', 'Ariana Grande', 'Ariana Grande', 'Hozier & Allison Russell', 'Chris Brown Featuring Davido & Lojay', 'Olivia Rodrigo', 'Morgan Wallen', 'Rich Amiri', 'Joyner Lucas & Jelly Roll', 'Drake', 'Good Neighbours', 'Xavi', 'Jordan Davis', 'Hozier', 'Olivia Rodrigo', 'Sam Hunt', 'Future, Metro Boomin, Travis Scott & Playboi Carti', 'Benson Boone', 'Teddy Swims', 'Hozier', 'Future, Metro Boomin & Travis Scott', 'Jack Harlow', 'Future & Metro Boomin', 'Future, Metro Boomin & The Weeknd', 'Ariana Grande', 'Beyonce', '¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', 'Future & Metro Boomin', 'Olivia Rodrigo', 'Zach Bryan Featuring Kacey Musgraves', 'Taylor Swift', 'Tate McRae', 'Noah Kahan', 'Tyla', 'Future & Metro Boomin', 'Djo', 'Doja Cat', 'SZA', 'Future & Metro Boomin', 'Luke Combs', 'SZA', 'Future & Metro Boomin', 'Sexyy Red', 'Flo Milli', '21 Savage', '4Batz Featuring Drake', 'Bryson Tiller', 'Future & Metro Boomin', 'Muni Long', 'Sabrina Carpenter', 'Future & Metro Boomin', 'Morgan Wallen Featuring Eric Church', 'Future, Metro Boomin & Rick Ross', 'HARDY', 'Future & Metro Boomin', 'Future & Metro Boomin', 'Dua Lipa', 'Doja Cat', 'Cardi B', 'Benson Boone', 'Justin Timberlake', 'Taylor Swift', 'Chayce Beckham', 'GloRilla', 'Luke Combs', 'Parker McCollum', 'Future & Metro Boomin', 'Dasha', 'Future & Metro Boomin', 'Jessie Murph & Jelly Roll', 'Xavi', 'Tate McRae', 'Olivia Rodrigo', 'Lainey Wilson', 'Ariana Grande', 'Ariana Grande', 'Future & Metro Boomin', 'BossMan Dlow', '310babii', 'Michael Marcagi', 'Nicki Minaj Featuring Lil Uzi Vert', 'YG Marley', 'Thomas Rhett Featuring Morgan Wallen', 'Peso Pluma, Tito Double P & Joel de La P', 'Artemas', 'Dua Lipa', 'Shakira & Cardi B', 'Xavi', 'The Weeknd, Jennie & Lily Rose Depp', 'Olivia Rodrigo', 'BigXthaPlug', 'Don Toliver', 'JID Featuring 21 Savage & Baby Tate', 'Bailey Zimmerman', 'Ariana Grande', 'Fuerza Regida', 'Nicki Minaj', 'FloyyMenor X Cris Mj', 'Kane Brown', 'Yeat', 'Ariana Grande', 'Ariana Grande', 'Hozier & Allison Russell', 'Chris Brown Featuring Davido & Lojay', 'Olivia Rodrigo', 'Morgan Wallen', 'Rich Amiri', 'Joyner Lucas & Jelly Roll', 'Drake', 'Good Neighbours', 'Xavi', 'Jordan Davis', 'Hozier', 'Olivia Rodrigo', 'Sam Hunt', 'Future, Metro Boomin & Kendrick Lamar', '-', '1', '1', 'Future, Metro Boomin, Travis Scott & Playboi Carti', '-', '2', '1', 'Benson Boone', '2', '2', '10', 'Teddy Swims', '1', '1', '33', 'Hozier', '-', '5', '1', 'Future, Metro Boomin & Travis Scott', '-', '6', '1', 'Jack Harlow', '4', '1', '20', 'Future & Metro Boomin', '-', '8', '1', 'Future, Metro Boomin & The Weeknd', '-', '9', '1', 'Ariana Grande', '3', '1', '3', 'Beyonce', '6', '1', '7', '¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', '5', '1', '7', 'Future & Metro Boomin', '-', '13', '1', 'Olivia Rodrigo', '-', '14', '1', 'Zach Bryan Featuring Kacey Musgraves', '7', '1', '31', 'Taylor Swift', '10', '1', '47', 'Tate McRae', '8', '3', '28', 'Noah Kahan', '12', '10', '26', 'Tyla', '20', '7', '26', 'Future & Metro Boomin', '-', '20', '1', 'Djo', '11', '11', '6', 'Doja Cat', '13', '7', '27', 'SZA', '14', '2', '67', 'Future & Metro Boomin', '-', '24', '1', 'Luke Combs', '18', '2', '53', 'SZA', '17', '6', '5', 'Future & Metro Boomin', '-', '27', '1', 'Sexyy Red', '23', '23', '2', 'Flo Milli', '15', '15', '15', '21 Savage', '22', '5', '11', '4Batz Featuring Drake', '19', '7', '12', 'Bryson Tiller', '24', '19', '6', 'Future & Metro Boomin', '-', '33', '1', 'Muni Long', '25', '20', '11', 'Sabrina Carpenter', '26', '26', '17', 'Future & Metro Boomin', '-', '36', '1', 'Morgan Wallen Featuring Eric Church', '28', '15', '27', 'Future, Metro Boomin & Rick Ross', '-', '38', '1', 'HARDY', '27', '27', '41', 'Future & Metro Boomin', '-', '40', '1', 'Future & Metro Boomin', '-', '41', '1', 'Dua Lipa', '29', '11', '20', 'Doja Cat', '32', '1', '34', 'Cardi B', '9', '9', '2', 'Benson Boone', '-', '45', '1', 'Justin Timberlake', '30', '19', '9', 'Taylor Swift', '31', '1', '22', 'Chayce Beckham', '45', '45', '13', 'GloRilla', '35', '35', '7', 'Luke Combs', '41', '26', '19', 'Parker McCollum', '42', '42', '23', 'Future & Metro Boomin', '-', '52', '1', 'Dasha', '59', '53', '3', 'Future & Metro Boomin', '-', '54', '1', 'Jessie Murph & Jelly Roll', '37', '35', '25', 'Xavi', '44', '20', '15', 'Tate McRae', '43', '34', '19', 'Olivia Rodrigo', '-', '58', '1', 'Lainey Wilson', '48', '48', '9', 'Ariana Grande', '34', '16', '3', 'Ariana Grande', '36', '1', '11', 'Future & Metro Boomin', '-', '62', '1', 'BossMan Dlow', '50', '49', '8', '310babii', '53', '53', '15', 'Michael Marcagi', '56', '56', '6', 'Nicki Minaj Featuring Lil Uzi Vert', '51', '24', '16', 'YG Marley', '62', '34', '9', 'Thomas Rhett Featuring Morgan Wallen', '55', '55', '13', 'Peso Pluma, Tito Double P & Joel de La P', '-', '69', '1', 'Artemas', '-', '70', '1', 'Dua Lipa', '61', '27', '6', 'Shakira & Cardi B', '-', '72', '1', 'Xavi', '-', '73', '1', 'The Weeknd, Jennie & Lily Rose Depp', '58', '51', '14', 'Olivia Rodrigo', '-', '75', '1', 'BigXthaPlug', '70', '65', '14', 'Don Toliver', '60', '38', '8', 'JID Featuring 21 Savage & Baby Tate', '57', '40', '20', 'Bailey Zimmerman', '67', '32', '13', 'Ariana Grande', '40', '17', '3', 'Fuerza Regida', '74', '66', '6', 'Nicki Minaj', '71', '15', '16', 'FloyyMenor X Cris Mj', '98', '83', '2', 'Kane Brown', '63', '50', '13', 'Yeat', '64', '42', '6', 'Ariana Grande', '52', '25', '3', 'Ariana Grande', '49', '23', '3', 'Hozier & Allison Russell', '-', '88', '1', 'Chris Brown Featuring Davido & Lojay', '73', '71', '8', 'Olivia Rodrigo', '-', '90', '1', 'Morgan Wallen', '78', '24', '9', 'Rich Amiri', '75', '60', '9', 'Joyner Lucas & Jelly Roll', '-', '93', '1', 'Drake', '69', '11', '19', 'Good Neighbours', '80', '77', '8', 'Xavi', '77', '46', '15', 'Jordan Davis', '81', '81', '4', 'Hozier', '-', '98', '1', 'Olivia Rodrigo', '-', '99', '1', 'Sam Hunt', '92', '92', '3', 'Future, Metro Boomin & Kendrick Lamar', '-', '1', '1', 'Future, Metro Boomin, Travis Scott & Playboi Carti', '-', '2', '1', 'Benson Boone', '2', '2', '10', 'Teddy Swims', '1', '1', '33', 'Hozier', '-', '5', '1', 'Future, Metro Boomin & Travis Scott', '-', '6', '1', 'Jack Harlow', '4', '1', '20', 'Future & Metro Boomin', '-', '8', '1', 'Future, Metro Boomin & The Weeknd', '-', '9', '1', 'Ariana Grande', '3', '1', '3', 'Beyonce', '6', '1', '7', '¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', '5', '1', '7', 'Future & Metro Boomin', '-', '13', '1', 'Olivia Rodrigo', '-', '14', '1', 'Zach Bryan Featuring Kacey Musgraves', '7', '1', '31', 'Taylor Swift', '10', '1', '47', 'Tate McRae', '8', '3', '28', 'Noah Kahan', '12', '10', '26', 'Tyla', '20', '7', '26', 'Future & Metro Boomin', '-', '20', '1', 'Djo', '11', '11', '6', 'Doja Cat', '13', '7', '27', 'SZA', '14', '2', '67', 'Future & Metro Boomin', '-', '24', '1', 'Luke Combs', '18', '2', '53', 'SZA', '17', '6', '5', 'Future & Metro Boomin', '-', '27', '1', 'Sexyy Red', '23', '23', '2', 'Flo Milli', '15', '15', '15', '21 Savage', '22', '5', '11', '4Batz Featuring Drake', '19', '7', '12', 'Bryson Tiller', '24', '19', '6', 'Future & Metro Boomin', '-', '33', '1', 'Muni Long', '25', '20', '11', 'Sabrina Carpenter', '26', '26', '17', 'Future & Metro Boomin', '-', '36', '1', 'Morgan Wallen Featuring Eric Church', '28', '15', '27', 'Future, Metro Boomin & Rick Ross', '-', '38', '1', 'HARDY', '27', '27', '41', 'Future & Metro Boomin', '-', '40', '1', 'Future & Metro Boomin', '-', '41', '1', 'Dua Lipa', '29', '11', '20', 'Doja Cat', '32', '1', '34', 'Cardi B', '9', '9', '2', 'Benson Boone', '-', '45', '1', 'Justin Timberlake', '30', '19', '9', 'Taylor Swift', '31', '1', '22', 'Chayce Beckham', '45', '45', '13', 'GloRilla', '35', '35', '7', 'Luke Combs', '41', '26', '19', 'Parker McCollum', '42', '42', '23', 'Future & Metro Boomin', '-', '52', '1', 'Dasha', '59', '53', '3', 'Future & Metro Boomin', '-', '54', '1', 'Jessie Murph & Jelly Roll', '37', '35', '25', 'Xavi', '44', '20', '15', 'Tate McRae', '43', '34', '19', 'Olivia Rodrigo', '-', '58', '1', 'Lainey Wilson', '48', '48', '9', 'Ariana Grande', '34', '16', '3', 'Ariana Grande', '36', '1', '11', 'Future & Metro Boomin', '-', '62', '1', 'BossMan Dlow', '50', '49', '8', '310babii', '53', '53', '15', 'Michael Marcagi', '56', '56', '6', 'Nicki Minaj Featuring Lil Uzi Vert', '51', '24', '16', 'YG Marley', '62', '34', '9', 'Thomas Rhett Featuring Morgan Wallen', '55', '55', '13', 'Peso Pluma, Tito Double P & Joel de La P', '-', '69', '1', 'Artemas', '-', '70', '1', 'Dua Lipa', '61', '27', '6', 'Shakira & Cardi B', '-', '72', '1', 'Xavi', '-', '73', '1', 'The Weeknd, Jennie & Lily Rose Depp', '58', '51', '14', 'Olivia Rodrigo', '-', '75', '1', 'BigXthaPlug', '70', '65', '14', 'Don Toliver', '60', '38', '8', 'JID Featuring 21 Savage & Baby Tate', '57', '40', '20', 'Bailey Zimmerman', '67', '32', '13', 'Ariana Grande', '40', '17', '3', 'Fuerza Regida', '74', '66', '6', 'Nicki Minaj', '71', '15', '16', 'FloyyMenor X Cris Mj', '98', '83', '2', 'Kane Brown', '63', '50', '13', 'Yeat', '64', '42', '6', 'Ariana Grande', '52', '25', '3', 'Ariana Grande', '49', '23', '3', 'Hozier & Allison Russell', '-', '88', '1', 'Chris Brown Featuring Davido & Lojay', '73', '71', '8', 'Olivia Rodrigo', '-', '90', '1', 'Morgan Wallen', '78', '24', '9', 'Rich Amiri', '75', '60', '9', 'Joyner Lucas & Jelly Roll', '-', '93', '1', 'Drake', '69', '11', '19', 'Good Neighbours', '80', '77', '8', 'Xavi', '77', '46', '15', 'Jordan Davis', '81', '81', '4', 'Hozier', '-', '98', '1', 'Olivia Rodrigo', '-', '99', '1', 'Sam Hunt', '92', '92', '3', 'Future, Metro Boomin & Kendrick Lamar', '-', '1', '1', 'Future, Metro Boomin, Travis Scott & Playboi Carti', '-', '2', '1', 'Benson Boone', '2', '2', '10', 'Teddy Swims', '1', '1', '33', 'Hozier', '-', '5', '1', 'Future, Metro Boomin & Travis Scott', '-', '6', '1', 'Jack Harlow', '4', '1', '20', 'Future & Metro Boomin', '-', '8', '1', 'Future, Metro Boomin & The Weeknd', '-', '9', '1', 'Ariana Grande', '3', '1', '3', 'Beyonce', '6', '1', '7', '¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', '5', '1', '7', 'Future & Metro Boomin', '-', '13', '1', 'Olivia Rodrigo', '-', '14', '1', 'Zach Bryan Featuring Kacey Musgraves', '7', '1', '31', 'Taylor Swift', '10', '1', '47', 'Tate McRae', '8', '3', '28', 'Noah Kahan', '12', '10', '26', 'Tyla', '20', '7', '26', 'Future & Metro Boomin', '-', '20', '1', 'Djo', '11', '11', '6', 'Doja Cat', '13', '7', '27', 'SZA', '14', '2', '67', 'Future & Metro Boomin', '-', '24', '1', 'Luke Combs', '18', '2', '53', 'SZA', '17', '6', '5', 'Future & Metro Boomin', '-', '27', '1', 'Sexyy Red', '23', '23', '2', 'Flo Milli', '15', '15', '15', '21 Savage', '22', '5', '11', '4Batz Featuring Drake', '19', '7', '12', 'Bryson Tiller', '24', '19', '6', 'Future & Metro Boomin', '-', '33', '1', 'Muni Long', '25', '20', '11', 'Sabrina Carpenter', '26', '26', '17', 'Future & Metro Boomin', '-', '36', '1', 'Morgan Wallen Featuring Eric Church', '28', '15', '27', 'Future, Metro Boomin & Rick Ross', '-', '38', '1', 'HARDY', '27', '27', '41', 'Future & Metro Boomin', '-', '40', '1', 'Future & Metro Boomin', '-', '41', '1', 'Dua Lipa', '29', '11', '20', 'Doja Cat', '32', '1', '34', 'Cardi B', '9', '9', '2', 'Benson Boone', '-', '45', '1', 'Justin Timberlake', '30', '19', '9', 'Taylor Swift', '31', '1', '22', 'Chayce Beckham', '45', '45', '13', 'GloRilla', '35', '35', '7', 'Luke Combs', '41', '26', '19', 'Parker McCollum', '42', '42', '23', 'Future & Metro Boomin', '-', '52', '1', 'Dasha', '59', '53', '3', 'Future & Metro Boomin', '-', '54', '1', 'Jessie Murph & Jelly Roll', '37', '35', '25', 'Xavi', '44', '20', '15', 'Tate McRae', '43', '34', '19', 'Olivia Rodrigo', '-', '58', '1', 'Lainey Wilson', '48', '48', '9', 'Ariana Grande', '34', '16', '3', 'Ariana Grande', '36', '1', '11', 'Future & Metro Boomin', '-', '62', '1', 'BossMan Dlow', '50', '49', '8', '310babii', '53', '53', '15', 'Michael Marcagi', '56', '56', '6', 'Nicki Minaj Featuring Lil Uzi Vert', '51', '24', '16', 'YG Marley', '62', '34', '9', 'Thomas Rhett Featuring Morgan Wallen', '55', '55', '13', 'Peso Pluma, Tito Double P & Joel de La P', '-', '69', '1', 'Artemas', '-', '70', '1', 'Dua Lipa', '61', '27', '6', 'Shakira & Cardi B', '-', '72', '1', 'Xavi', '-', '73', '1', 'The Weeknd, Jennie & Lily Rose Depp', '58', '51', '14', 'Olivia Rodrigo', '-', '75', '1', 'BigXthaPlug', '70', '65', '14', 'Don Toliver', '60', '38', '8', 'JID Featuring 21 Savage & Baby Tate', '57', '40', '20', 'Bailey Zimmerman', '67', '32', '13', 'Ariana Grande', '40', '17', '3', 'Fuerza Regida', '74', '66', '6', 'Nicki Minaj', '71', '15', '16', 'FloyyMenor X Cris Mj', '98', '83', '2', 'Kane Brown', '63', '50', '13', 'Yeat', '64', '42', '6', 'Ariana Grande', '52', '25', '3', 'Ariana Grande', '49', '23', '3', 'Hozier & Allison Russell', '-', '88', '1', 'Chris Brown Featuring Davido & Lojay', '73', '71', '8', 'Olivia Rodrigo', '-', '90', '1', 'Morgan Wallen', '78', '24', '9', 'Rich Amiri', '75', '60', '9', 'Joyner Lucas & Jelly Roll', '-', '93', '1', 'Drake', '69', '11', '19', 'Good Neighbours', '80', '77', '8', 'Xavi', '77', '46', '15', 'Jordan Davis', '81', '81', '4', 'Hozier', '-', '98', '1', 'Olivia Rodrigo', '-', '99', '1', 'Sam Hunt', '92', '92', '3', 'Future, Metro Boomin & Kendrick Lamar', '-', '1', '1', 'Future, Metro Boomin, Travis Scott & Playboi Carti', '-', '2', '1', 'Benson Boone', '2', '2', '10', 'Teddy Swims', '1', '1', '33', 'Hozier', '-', '5', '1', 'Future, Metro Boomin & Travis Scott', '-', '6', '1', 'Jack Harlow', '4', '1', '20', 'Future & Metro Boomin', '-', '8', '1', 'Future, Metro Boomin & The Weeknd', '-', '9', '1', 'Ariana Grande', '3', '1', '3', 'Beyonce', '6', '1', '7', '¥$: Ye & Ty Dolla $ign Featuring Rich The Kid & Playboi Carti', '5', '1', '7', 'Future & Metro Boomin', '-', '13', '1', 'Olivia Rodrigo', '-', '14', '1', 'Zach Bryan Featuring Kacey Musgraves', '7', '1', '31', 'Taylor Swift', '10', '1', '47', 'Tate McRae', '8', '3', '28', 'Noah Kahan', '12', '10', '26', 'Tyla', '20', '7', '26', 'Future & Metro Boomin', '-', '20', '1', 'Djo', '11', '11', '6', 'Doja Cat', '13', '7', '27', 'SZA', '14', '2', '67', 'Future & Metro Boomin', '-', '24', '1', 'Luke Combs', '18', '2', '53', 'SZA', '17', '6', '5', 'Future & Metro Boomin', '-', '27', '1', 'Sexyy Red', '23', '23', '2', 'Flo Milli', '15', '15', '15', '21 Savage', '22', '5', '11', '4Batz Featuring Drake', '19', '7', '12', 'Bryson Tiller', '24', '19', '6', 'Future & Metro Boomin', '-', '33', '1', 'Muni Long', '25', '20', '11', 'Sabrina Carpenter', '26', '26', '17', 'Future & Metro Boomin', '-', '36', '1', 'Morgan Wallen Featuring Eric Church', '28', '15', '27', 'Future, Metro Boomin & Rick Ross', '-', '38', '1', 'HARDY', '27', '27', '41', 'Future & Metro Boomin', '-', '40', '1', 'Future & Metro Boomin', '-', '41', '1', 'Dua Lipa', '29', '11', '20', 'Doja Cat', '32', '1', '34', 'Cardi B', '9', '9', '2', 'Benson Boone', '-', '45', '1', 'Justin Timberlake', '30', '19', '9', 'Taylor Swift', '31', '1', '22', 'Chayce Beckham', '45', '45', '13', 'GloRilla', '35', '35', '7', 'Luke Combs', '41', '26', '19', 'Parker McCollum', '42', '42', '23', 'Future & Metro Boomin', '-', '52', '1', 'Dasha', '59', '53', '3', 'Future & Metro Boomin', '-', '54', '1', 'Jessie Murph & Jelly Roll', '37', '35', '25', 'Xavi', '44', '20', '15', 'Tate McRae', '43', '34', '19', 'Olivia Rodrigo', '-', '58', '1', 'Lainey Wilson', '48', '48', '9', 'Ariana Grande', '34', '16', '3', 'Ariana Grande', '36', '1', '11', 'Future & Metro Boomin', '-', '62', '1', 'BossMan Dlow', '50', '49', '8', '310babii', '53', '53', '15', 'Michael Marcagi', '56', '56', '6', 'Nicki Minaj Featuring Lil Uzi Vert', '51', '24', '16', 'YG Marley', '62', '34', '9', 'Thomas Rhett Featuring Morgan Wallen', '55', '55', '13', 'Peso Pluma, Tito Double P & Joel de La P', '-', '69', '1', 'Artemas', '-', '70', '1', 'Dua Lipa', '61', '27', '6', 'Shakira & Cardi B', '-', '72', '1', 'Xavi', '-', '73', '1', 'The Weeknd, Jennie & Lily Rose Depp', '58', '51', '14', 'Olivia Rodrigo', '-', '75', '1', 'BigXthaPlug', '70', '65', '14', 'Don Toliver', '60', '38', '8', 'JID Featuring 21 Savage & Baby Tate', '57', '40', '20', 'Bailey Zimmerman', '67', '32', '13', 'Ariana Grande', '40', '17', '3', 'Fuerza Regida', '74', '66', '6', 'Nicki Minaj', '71', '15', '16', 'FloyyMenor X Cris Mj', '98', '83', '2', 'Kane Brown', '63', '50', '13', 'Yeat', '64', '42', '6', 'Ariana Grande', '52', '25', '3', 'Ariana Grande', '49', '23', '3', 'Hozier & Allison Russell', '-', '88', '1', 'Chris Brown Featuring Davido & Lojay', '73', '71', '8', 'Olivia Rodrigo', '-', '90', '1', 'Morgan Wallen', '78', '24', '9', 'Rich Amiri', '75', '60', '9', 'Joyner Lucas & Jelly Roll', '-', '93', '1', 'Drake', '69', '11', '19', 'Good Neighbours', '80', '77', '8', 'Xavi', '77', '46', '15', 'Jordan Davis', '81', '81', '4', 'Hozier', '-', '98', '1', 'Olivia Rodrigo', '-', '99', '1', 'Sam Hunt', '92', '92', '3']

In [349]:
TOP_100_SONGS=pd.DataFrame({})
TOP_100_SONGS['Song_name']=Song_Name[:100]
TOP_100_SONGS['Artist_name']=Artist_Name[:100]
TOP_100_SONGS['Last_week_rank']=Last_Week_Rank[:100]
TOP_100_SONGS['Peak_rank']=Peak_Rank[:100]
TOP_100_SONGS['Weeks_on_board']= Weeks_on_Board[:100]
TOP_100_SONGS

,Song_name,Artist_name,Last_week_rank,Peak_rank,Weeks_on_board
0,Like That,"Future, Metro Boomin & Kendrick Lamar",-,1,1
1,Type Shit,-,-,2,1
2,Beautiful Things,1,2,2,10
3,Lose Control,1,1,1,33
4,Too Sweet,"Future, Metro Boomin, Travis Scott & Playboi C...",-,5,1
...,...,...,...,...,...
95,La Victima,1,77,46,15
96,Tucson Too Late,Luke Combs,81,81,4
97,Empire Now,18,-,98,1
98,Girl I've Always Been,2,-,99,1
99,Outskirts,53,92,92,3

# Q-4

In [350]:
driver=webdriver.Chrome()
driver.maximize_window()

In [351]:
driver.get('https://github.com/')
time.sleep(2)

In [352]:
Open= driver.find_element(By.XPATH, '/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
Open.click()

In [353]:
Trending= driver.find_element(By.XPATH, '/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/div[3]/ul/li[2]/a')
try:
    Trending.click()
except ElementNotInteractableException:
    driver.get(Trending.get_attribute('href'))

In [354]:
Repository_Title=[]
Repository_Description=[] 
Contributors_Count=[] 
Language_Used=[]

In [358]:
title= driver.find_elements(By.XPATH, '//h2[@class="h3 lh-condensed"]/a')
for i in title:
    Repository_Title.append(i.text)
    
    
desc= driver.find_elements(By.XPATH, '//p[@class="col-9 color-fg-muted my-1 pr-4"]')
for i in desc:
    try:
        Repository_Description.append(i.text)
    except:
        Repository_Description.append("_")
        
    
    
    
count= driver.find_elements(By.XPATH, '//span[@class="d-inline-block float-sm-right"]')
for i in count:
    try:
        Contributors_Count.append(i.text)
    except:
        Contributors_Count.append("-")
        
Language= driver.find_elements(By.XPATH, '//span[@class="d-inline-block ml-0 mr-3"]/span[2]')
for i in Language:
    try:
        Language_Used.append(i.text)
    except:
        Language_Used.append("_")

In [359]:
Repositoriy=pd.DataFrame({})
Repositoriy['Repository Title']=Repository_Title[0:24]
Repositoriy['Repository Description']=Repository_Description[0:24]
Repositoriy['Contributors Count']=Contributors_Count[0:24]
Repositoriy['Language Used']=Language_Used[0:24]
Repositoriy

,Repository Title,Repository Description,Contributors Count,Language Used
0,plandex-ai / plandex,An AI coding engine for complex tasks,"1,435 stars today",Go
1,HardhatChad / ore-cli,计算机自学指南,377 stars today,Rust
2,PKUFlyingPig / cs-self-learning,AstroNvim is an aesthetic and feature-rich neo...,986 stars today,HTML
3,HardhatChad / ore,freeCodeCamp.org's open-source codebase and cu...,129 stars today,Rust
4,AstroNvim / AstroNvim,📚 Freely available programming books,177 stars today,Lua
5,freeCodeCamp / freeCodeCamp,A collective list of free APIs,135 stars today,TypeScript
6,EbookFoundation / free-programming-books,free,186 stars today,Python
7,public-apis / public-apis,Reaching LLaMA2 Performance with 0.1M Dollars,252 stars today,Go
8,aurora-develop / aurora,🚀🎉📚 SaaS Boilerplate built with Next.js + Tail...,180 stars today,Python
9,myshell-ai / JetMoE,Windows in a Docker container.,105 stars today,TypeScript
10,ixartz / SaaS-Boilerplate,"Interactive roadmaps, guides and other educati...",341 stars today,Shell
11,dockur / windows,SearXNG is a free internet metasearch engine w...,377 stars today,TypeScript
12,kamranahmedse / developer-roadmap,Vim-fork focused on extensibility and usability,291 stars today,Python
13,searxng / searxng,🎓 Path to a free self-taught education in Comp...,329 stars today,TypeScript
14,cloudflare / orange,[GPT beats diffusion🔥] [scaling laws in visual...,49 stars today,Rust
15,availproject / avail-light,Learn how to design large-scale systems. Prep ...,63 stars today,Vim Script
16,neovim / neovim,"A React Framework for building internal tools,...",40 stars today,Rust
17,availproject / avail,A multi core friendly rigid body physics and c...,40 stars today,Python
18,ossu / computer-science,⛓️ Langflow is a dynamic graph where each node...,299 stars today,TypeScript
19,FoundationVision / VAR,An AI coding engine for complex tasks,334 stars today,Python
20,pagefaultgames / pokerogue,计算机自学指南,5 stars today,TypeScript
21,donnemartin / system-design-primer,AstroNvim is an aesthetic and feature-rich neo...,199 stars today,C++
22,refinedev / refine,freeCodeCamp.org's open-source codebase and cu...,75 stars today,JavaScript
23,jrouwe / JoltPhysics,📚 Freely available programming books,30 stars today,Go

# Q-3

In [329]:
driver=webdriver.Chrome()
driver.maximize_window()

In [330]:
driver.get("http://statisticstimes.com/")
time.sleep(2)

In [331]:
Economy= driver.find_element(By.XPATH, '/html/body/div[2]/div[1]/div[2]/div[2]/button')
Economy.click()
India=driver.find_element(By.XPATH, "/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]")
driver.get(India.get_attribute('href'))

In [332]:
GDP_Indian_States=driver.find_element(By.XPATH, "/html/body/div[2]/div[2]/div[2]/ul/li[1]/a")
driver.get(GDP_Indian_States.get_attribute('href'))

In [333]:
Rank=[] 
State=[] 
GSDP_Year_2021_to_Year_2022=[] 
GSDP_Year_2022_to_Year_2023=[] 
Share_Year_2021_to_2022=[] 
GDP_Dollar_Billion=[]

In [336]:
rank= driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td')
for i in rank:
    Rank.append(i.text)
    
state= driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[2]')
for i in state:
    State.append(i.text)
    
    
Gsdp_21_22= driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[5]')
for i in Gsdp_21_22:
    GSDP_Year_2021_to_Year_2022.append(i.text)
    

Gsdp_22_23= driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[4]')
for i in Gsdp_22_23:
    GSDP_Year_2022_to_Year_2023.append(i.text)
    
share= driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[6]')
for i in share:
    Share_Year_2021_to_2022.append(i.text)
    
    
dollar= driver.find_elements(By.XPATH, '//table[@class="display dataTable"]/tbody/tr/td[7]')
for i in dollar:
    GDP_Dollar_Billion.append(i.text)

In [338]:
print(State)

['Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Odisha', 'Bihar', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Odisha', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Manipur', 'Sikkim', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Odisha', 'Bihar', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Odisha', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Manipur', 'Sikkim', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Odisha', 'Bihar', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Sikkim', 'Manipur', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands', 'Maharashtra', 'Tamil Nadu', 'Karnataka', 'Uttar Pradesh', 'Gujarat', 'West Bengal', 'Rajasthan', 'Andhra Pradesh', 'Telangana', 'Madhya Pradesh', 'Kerala', 'Delhi', 'Haryana', 'Bihar', 'Odisha', 'Punjab', 'Assam', 'Chhattisgarh', 'Jharkhand', 'Uttarakhand', 'Jammu & Kashmir', 'Himachal Pradesh', 'Goa', 'Tripura', 'Chandigarh', 'Puducherry', 'Meghalaya', 'Manipur', 'Sikkim', 'Arunachal Pradesh', 'Nagaland', 'Mizoram', 'Andaman & Nicobar Islands']

In [340]:
GSDP=pd.DataFrame({})
GSDP['Rank']=Rank[:33]
GSDP['State']=State[:33]
GSDP['GSDP (Cr INR at Current prices) Year 2021-2022']=GSDP_Year_2021_to_Year_2022[:33] 
GSDP['GSDP (Cr INR at Current prices) Year 2022-2023']=GSDP_Year_2022_to_Year_2023[:33]
GSDP['Share Year 2021-2022']=Share_Year_2021_to_2022[:33]
GSDP['GDP ($ Billion)']=GDP_Dollar_Billion[:33]
GSDP

,Rank,State,GSDP (Cr INR at Current prices) Year 2021-2022,GSDP (Cr INR at Current prices) Year 2022-2023,Share Year 2021-2022,GDP ($ Billion)
0,1,Maharashtra,"3,108,022",-,13.17%,414.928
1,Maharashtra,Tamil Nadu,"2,071,286","2,364,514",8.78%,276.522
2,-,Karnataka,"1,978,094","2,269,995",8.38%,264.080
3,-,Uttar Pradesh,"1,975,595","2,258,040",8.37%,263.747
4,"3,108,022",Gujarat,"1,928,683","2,230,609",8.17%,257.484
5,13.17%,West Bengal,"1,329,238","1,531,758",5.63%,177.456
6,414.928,Rajasthan,"1,193,489","1,365,849",5.06%,159.334
7,-,Andhra Pradesh,"1,148,471","1,303,524",4.87%,153.324
8,-,Telangana,"1,124,204","1,308,034",4.76%,150.084
9,"2,027,971",Madhya Pradesh,"1,092,964","1,246,471",4.63%,145.913
10,2,Kerala,"934,542","1,046,188",3.96%,124.764
11,Tamil Nadu,Delhi,"881,336","1,014,688",3.73%,117.660
12,"2,700,109",Haryana,"868,905","984,055",3.68%,116.001
13,"2,364,514",Odisha,"662,886","753,177",2.81%,88.497
14,"2,071,286",Bihar,"650,302","751,396",2.76%,86.817
15,8.78%,Punjab,"617,192","676,164",2.62%,82.397
16,276.522,Assam,"411,454","493,167",1.74%,54.930
17,"1,572,601",Chhattisgarh,"410,525","464,399",1.74%,54.806
18,"1,453,321",Jharkhand,"358,863","393,722",1.52%,47.909
19,"1,343,287",Uttarakhand,"267,143","303,781",1.13%,35.664
20,3,Jammu & Kashmir,"193,352","224,226",0.82%,25.813
21,Karnataka,Himachal Pradesh,"172,162","191,728",0.73%,22.984
22,"2,500,733",Goa,"84,266","93,672",0.36%,11.250
23,"2,269,995",Tripura,"62,550","72,636",0.27%,8.351
24,"1,978,094",Chandigarh,"46,096","54,285",0.20%,6.154
25,8.38%,Puducherry,"43,810","49,643",0.19%,5.849
26,264.080,Meghalaya,"38,785","42,697",0.16%,5.178
27,"1,423,229",Sikkim,"37,557","42,756",0.16%,5.014
28,"1,335,052",Manipur,"36,594",-,0.16%,4.885
29,"1,235,377",Arunachal Pradesh,"34,775","39,630",0.15%,4.643
30,4,Nagaland,"31,038","35,643",0.13%,4.144
31,Uttar Pradesh,Mizoram,"27,824",-,0.12%,3.715
32,"2,547,861",Andaman & Nicobar Islands,"10,371",-,0.04%,1.385